import { LayoutProviders } from '@app/_/LayoutProviders';
import '@app/_/styles/globals.css';
import { wagmiConfig } from '@config/wagmi';
import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import { type ReactNode } from 'react';
import { cookieToInitialState } from 'wagmi';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get('cookie')
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProviders initialState={initialState}>
          {children}
        </LayoutProviders>
      </body>
    </html>
  );
};

export default RootLayout;
